betri install, COSMIC removed for faster testing

diff --git a/programs/nix-iso-setup b/programs/nix-iso-setup
--- a/programs/nix-iso-setup
+++ b/programs/nix-iso-setup
@@ -4,11 +4,10 @@
 repo="SputNix"
 
 main() {
-    # connect to wifi
+    # Clone the repository
     git clone https://github.com/GitHver/nixisotemp.git ./"$repo"
-    # cd ~/"$repo"
-    # rm -rf .git
 
+    # Get variables to replace in file
     userandhost
     partitioning
     localization
@@ -37,6 +36,24 @@ partitioning() {
     # echo "is this the correct disk?: $disktype"
     # input-accept
     # done
+    printf "Do you want your filesystem to be encrypted?"
+    inputAccept || return
+    encrypt=true
+
+    while true; do
+        printf "type in your decryption passphrase: "
+        read -s decrypt_passphrase # POSIX undefined
+        printf "\n         retype in your passphrase: "
+        read -s reread_decrypt_passphrase # POSIX undefined
+
+        if [ "$decrypt_passphrase" = "$reread_decrypt_passphrase" ]; then
+            echo "setting encryption..."
+            break
+        fi
+        printf "\npassphrases do not match" >& 2
+    done
+    # "$decrypt_passphrase" | sudo tee /tmp/decrypt_passphrase.txt
+    echo -n "$decrypt_passphrase" | sudo tee ./decrypt_passphrase.txt # POSIX undefined
 }
 
 localization() {
@@ -63,32 +80,13 @@ testallation() {
         hostname = $host_name,
         username = $user_name,
         displayame = $display_name,
+        language = $selected_language,
+        formatting = $selected_formatting,
         disk to mount = $disktype,
-        language = $selected_language
-        formatting = $selected_formatting
+        encryption = $encrypt
     " 
     sleep 5
     echo "done!"
-}
-
-# This function can be called to take input from the user on whether to proceed.
-inputAccept() {
-    for i in 1 2 3; do 
-        printf "continue? [Y/N]: " >&2
-        read input
-        case $input in
-        [yY]) return 0 ;;
-        [nN]) return 1 ;;
-        *)
-            if [ $i -lt  3 ]; then
-                sleep 0.5
-            else
-                echo "3 invalid answers, aborting" >&2
-                exit 2
-            fi
-            ;;
-        esac
-    done
 }
 
 installation() {
@@ -104,12 +102,15 @@ installation() {
     # rename host
     mv ./hosts/your-hostname ./hosts/"$host_name"
 
-    # Set the correct disktype
-    sed -i "s,/dev/disktype,/dev/$disktype," ./hosts/"$host_name"/disko.nix
-
     # change locale
     sed -i "s/language-locale/$selected_language/" ./configs/configuration.nix
     sed -i "s/formatting-locale/${selected_formatting:-$selected_language}/" ./configs/configuration.nix
+
+    # Set the correct disktype
+    sed -i "s,/dev/disktype,/dev/$disktype," ./hosts/"$host_name"/disko.nix
+    if $encrypt; then
+        sed -i "s/encrypt=false/encrypt=true/" ./hosts/"$host_name"/disko.nix
+    fi
 
     # mounting the disk
     sudo nix --experimental-features "nix-command flakes" run github:nix-community/disko -- --mode disko ./hosts/"$host_name"/disko.nix
@@ -123,6 +124,27 @@ installation() {
 
     # Start the install
     sudo nixos-install --flake .#"$host_name"
+}
+
+# This function can be called to take input from the user on whether to proceed.
+inputAccept() {
+    for i in 1 2 3; do 
+        printf "continue? [Y/N]: " >& 2
+        read input
+        case $input in
+        [yY]) return 0 ;;
+        [nN]) return 1 ;;
+        *)
+            if [ $i -lt  3 ]; then
+                sleep 0.5
+            else
+                echo "3 invalid answers, aborting" >& 2
+                exit 2
+            fi
+            ;;
+        esac
+        echo "not \`y\` or \`n\`. try again" >& 2
+    done
 }
 
 main "$@"
