$repo variable fix

diff --git a/programs/nix-iso-setup b/programs/nix-iso-setup
--- a/programs/nix-iso-setup
+++ b/programs/nix-iso-setup
@@ -5,8 +5,7 @@ repo="SputNix"
 
 main() {
     # connect to wifi
-    git clone https://github.com/GitHver/nixisotemp.git ./"repo"
-    # # git clone git@github.com/GitHver/nixisotemp.git ~/"$repo"
+    git clone https://github.com/GitHver/nixisotemp.git ./"$repo"
     cd ~/"repo"
     rm -rf .git
 
@@ -20,7 +19,7 @@ main() {
     #     change anything?
 
     installation
-    # testallation
+    testallation
 }
 
 userandhost() {
@@ -51,7 +50,7 @@ localization() {
     read selected_language
 
     echo "use another language for formatting? (time, date, messurments, currency, etc)"
-    input-accept || return
+    inputAccept || return
 
     printf "Type in your language to use for formatting: "
     read selected_formatting
@@ -62,7 +61,7 @@ localization() {
 }
 
 testallation() {
-    echo "doing the thing..."
+    echo "set values..."
     echo "${display_name:=$user_name}" > /dev/null
     echo "${selected_formatting:=$selected_language}" > /dev/null
     echo "
@@ -73,18 +72,41 @@ testallation() {
         language = $selected_language
         formatting = $selected_formatting
     " 
-    sleep 1
+    sleep 5
     echo "done!"
 }
 
+# This function can be called to take input from the user on whether to proceed.
+inputAccept() {
+    for i in 1 2 3; do 
+        printf "continue? [Y/N]: " >&2
+        read input
+        case $input in
+        [yY]) return 0 ;;
+        [nN]) return 1 ;;
+        *)
+            if [ $i -lt  3 ]; then
+                sleep 0.5
+            else
+                echo "3 invalid answers, aborting" >&2
+                exit 2
+            fi
+            ;;
+        esac
+    done
+}
+
 installation() {
-    # rename host
-    mv ./hosts/your-hostname ./hosts/"$host_name"
+
+    cd ~/$repo
 
     # rename user
+    sed -i "s/your_username/$user_name/" ./hosts/your-hostname/users/your-user.nix
+    sed -i "s/your_displayname/${display_name:=$user_name}/" ./hosts/your-hostname/users/your-user.nix
     mv ./hosts/your-hostname/users/your-user.nix ./hosts/your-hostname/"$user_name".nix
-    sed -i "s/your_username/$user_name/" ./hosts/"$host_name"/users/"$user_name".nix
-    sed -i "s/your_displayname/${display_name:=$user_name}/" ./hosts/"$host_name"/users/"$user_name".nix
+
+    # rename host
+    mv ./hosts/your-hostname ./hosts/"$host_name"
 
     # Set the correct disktype
     sed -i "s,/dev/disktype,/dev/$disktype,"
